### PR TITLE
CC-16593: Fix CSS build in production mode

### PR DESCRIPTION
**Pull request by andrew-maslov**
## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by SassNinja** [comment]
@andrew-maslov could you provide some more context? What error is this **downgrade** of `optimize-css-assets-webpack-plugin` solving?

**Comment by andrew-maslov** [comment]
@SassNinja In the `optimize-css-assets-webpack-plugin`: `6.0.1` was found the issue:
```
An error occurred while creating configuration Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/data/node_modules/postcss/lib/processor.js:145:15)
    at new Processor (/data/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/data/node_modules/postcss/lib/postcss.js:73:10)
    at cssnanoPlugin (/data/node_modules/cssnano/src/index.js:167:10)
    at getDefaultProcessor (/data/node_modules/@spryker/oryx-for-zed/node_modules/optimize-css-assets-webpack-plugin/src/index.js:9:19)
    at new OptimizeCssAssetsWebpackPlugin (/data/node_modules/@spryker/oryx-for-zed/node_modules/optimize-css-assets-webpack-plugin/src/index.js:30:9)
    at Object.getConfiguration (/data/node_modules/@spryker/oryx-for-zed/lib/webpack.config.js:203:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by SassNinja** [comment]
I guess your issue exists since `6.0.0` because this introduced postcss: https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/v6.0.0/src/index.js#L6

However I'm surprised about this error message because it's doesn't appear in any issue of `ptimize-css-assets-webpack-plugin`...

**Review by tolerants — APPROVED** [review]

**Comment by stefpb** [comment]
We solve this problem with `npm install postcss`, so no downgrade of `optimize-css-assets-webpack-plugin` necessary.

**Pull request merged**
